set(CMAKE_SYSTEM_NAME iOS)
set(CMAKE_SYSTEM_PROCESSOR $ENV{CONAN_THEOS_TARGET_ARCH})
set(CMAKE_SYSROOT $ENV{CONAN_THEOS_TARGET_SDK_ROOT})
set(CMAKE_OSX_SYSROOT $ENV{CONAN_THEOS_TARGET_SDK_ROOT})
set(CMAKE_OSX_ARCHITECTURES $ENV{CONAN_THEOS_TARGET_ARCH})
set(CMAKE_OSX_DEPLOYMENT_TARGET $ENV{CONAN_THEOS_TARGET_OS_VERSION})

include_directories(
    $ENV{THEOS}/include
    $ENV{THEOS}/vendor/include
    $ENV{THEOS}/include/_fallback
)

add_compile_definitions(
    TARGET_IPHONE=1
)

set(CMAKE_C_COMPILER $ENV{THEOS}/toolchain/linux/iphone/bin/clang)
set(CMAKE_C_COMPILER_TARGET $ENV{CONAN_THEOS_TARGET_ARCH}-apple-ios$ENV{CONAN_THEOS_TARGET_OS_VERSION})

set(CMAKE_CXX_COMPILER $ENV{THEOS}/toolchain/linux/iphone/bin/clang++)
set(CMAKE_CXX_COMPILER_TARGET $ENV{CONAN_THEOS_TARGET_ARCH}-apple-ios$ENV{CONAN_THEOS_TARGET_OS_VERSION})
